local lspconfig = require("lspconfig")

-- PHP language server (intelephense)
lspconfig.intelephense.setup({
	settings = {
		intelephense = {
			stubs = {
				"bcmath",
				"bz2",
				"Core",
				"curl",
				"date",
				"dom",
				"fileinfo",
				"filter",
				"gd",
				"gettext",
				"hash",
				"iconv",
				"imap",
				"intl",
				"json",
				"libxml",
				"mbstring",
				"mcrypt",
				"mysql",
				"mysqli",
				"password",
				"pcntl",
				"pcre",
				"PDO",
				"pdo_mysql",
				"Phar",
				"readline",
				"regex",
				"session",
				"SimpleXML",
				"sockets",
				"sodium",
				"standard",
				"superglobals",
				"tokenizer",
				"xml",
				"xdebug",
				"xmlreader",
				"xmlwriter",
				"yaml",
				"zip",
				"zlib",
				"genesis-stubs",
				"polylang-stubs",
			},
			environment = {
				document_root = ".",
				exclude = {
					"**/.git/**",
					"**/.svn/**",
					"**/.hg/**",
					"**/CVS/**",
					"**/.DS_Store/**",
					"**/node_modules/**",
					"**/bower_components/**",
					"**/vendor/**/{Tests,tests}/**",
					"/var/**",
					"/framework/**",
					"**/vendor/**/{Example,example,Examples,examples}/**",
				},
			},
			files = {
				maxSize = 5000000,
			},
		},
	},
	capabilities = vim.lsp.protocol.make_client_capabilities(),
	on_attach = require("user.src.lsp-handler").on_attach,
})

-- local servers = require("lspconfig.util").available_servers()
-- require("user.util.lsp").setup_servers(servers)
