# Add your own custom alias in the custom/aliases directory. Aliases placed
# here will override ones with the same name in the main alias directory.
alias viw='vi ~/fo/inc/woocommerce.php'
alias via='vi ~/fo/inc/admin.php'
alias vif='vi ~/fo/functions.php'
alias cdp='cd ~/plugins/'
alias cdf='cd ~/fo/'
alias cdi='cd ~/fo/inc/'
alias c='cd'
alias v='vi'
alias n='nvim'
alias grep='grep --exclude-dir=".git"'
alias grepr='grep -R --exclude-dir=".git"'
alias grepv='grep -v'
alias taildevp='tail -f /var/log/php/tgdev1.transitionsgroup.net-error_log'
alias videvp='tail -f /var/log/php/tgdev1.transitionsgroup.net-error_log'
alias taildeva='tail -f /var/log/apache2/tgdev1.transitionsgroup.net-error_log'
alias videva='tail -f /var/log/apache2/tgdev1.transitionsgroup.net-error_log'
alias pw='pwd'
alias cmp='composer'

alias gstat='git fetch && git status'
alias gstatus='git fetch && git status'
alias gcommit='git commit'
alias glog='git log'
alias gpush='git push'
alias gpull='git pull'

alias g='git'
alias gs='git fetch && git status'
alias gc='git commit'
alias gcm='git commit -m'
alias gpsh='git push'
alias gpl='git pull'
alias gpll='git pull'
alias gl='git log'
alias gd='git diff'
alias ga='git add'

alias diff='diff --color=always'
